apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    app: udagram-frontend
spec:
  ports:
  - name: "frontend"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-feed-frontend
  type: LoadBalancer
